### ISSUE TITLE
Unable to run sample files

### ISSUE THREAD

**Issue by YvonneChenCS** [rajewsky-lab/novosparc#27]
Hi, I think I successfully installed novosparc, but when I tried to run the sample files, I keep getting the following error message: 

opt/anaconda3/lib/python3.7/site-packages/pysal/lib/weights/util.py:19: UserWarning: geopandas not available. Some functionality will be disabled.
  warn('geopandas not available. Some functionality will be disabled.')
/opt/anaconda3/lib/python3.7/site-packages/pysal/explore/spaghetti/util.py:13: UserWarning: geopandas/shapely not available. Some functionality will be disabled.
  warn(err_msg)
Traceback (most recent call last):
  File "reconstruct_bdtnp_with_markers.py", line 5, in <module>
    import novosparc
  File "/Users/c/Desktop/novosparc-master/novosparc/__init__.py", line 17, in <module>
    from . import analysis
  File "/Users/c/Desktop/novosparc-master/novosparc/analysis/__init__.py", line 1, in <module>
    from ._analysis import morans
  File "/Users/c/Desktop/novosparc-master/novosparc/analysis/_analysis.py", line 2, in <module>
    import pysal.lib
  File "/opt/anaconda3/lib/python3.7/site-packages/pysal/__init__.py", line 3, in <module>
    from . import explore
  File "/opt/anaconda3/lib/python3.7/site-packages/pysal/explore/__init__.py", line 6, in <module>
    from . import segregation
  File "/opt/anaconda3/lib/python3.7/site-packages/pysal/explore/segregation/__init__.py", line 7, in <module>
    from . import aspatial
  File "/opt/anaconda3/lib/python3.7/site-packages/pysal/explore/segregation/aspatial/__init__.py", line 1, in <module>
    from .aspatial_indexes import *
  File "/opt/anaconda3/lib/python3.7/site-packages/pysal/explore/segregation/aspatial/aspatial_indexes.py", line 10, in <module>
    import geopandas as gpd
  File "/opt/anaconda3/lib/python3.7/site-packages/geopandas/__init__.py", line 5, in <module>
    from geopandas.io.file import read_file  # noqa
  File "/opt/anaconda3/lib/python3.7/site-packages/geopandas/io/file.py", line 6, in <module>
    import fiona
  File "/opt/anaconda3/lib/python3.7/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/opt/anaconda3/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/opt/anaconda3/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libgif.7.dylib
  Referenced from: /opt/anaconda3/lib/libgdal.20.dylib
  Reason: image not found

As a side note, I installed nhvosparc through conda.
Thank you very much.

**Comment by enessenel** [comment]
Hi, could you please check which pysal version you have installed and let me know? Upgrading it to version 2.1.0 through conda might help

**Comment by enessenel** [comment]
pysal dependency is removed so it should function now without the version issues.
